const BOOKING_IMAGES = {
  alexaChu: require("../../assets/images/booking/alexa-chu.png"),
  bca: require("../../assets/images/booking/bca.png"),
  bni: require("../../assets/images/booking/bni.png"),
  bri: require("../../assets/images/booking/bri.png"),
  bookmark: require("../../assets/images/booking/bookmark.png"),
  bookmarkActive: require("../../assets/images/booking/bookmark-active.png"),
  check: require("../../assets/images/booking/check.png"),
  chevronLeft: require("../../assets/images/booking/chevron-left.png"),
  chevronRight: require("../../assets/images/booking/chevron-right.png"),
  clintonSander: require("../../assets/images/booking/clinton-sander.png"),
  copy: require("../../assets/images/booking/copy.png"),
  dillySimsons: require("../../assets/images/booking/dilly-simsons.png"),
  greyWillis: require("../../assets/images/booking/grey-willis.png"),
  image1: require("../../assets/images/booking/image-1.png"),
  image2: require("../../assets/images/booking/image-2.png"),
  image3: require("../../assets/images/booking/image-3.png"),
  image4: require("../../assets/images/booking/image-4.png"),
  image5: require("../../assets/images/booking/image-5.png"),
  image6: require("../../assets/images/booking/image-6.png"),
  lauraLee: require("../../assets/images/booking/laura-lee.png"),
  leftArrow: require("../../assets/images/booking/left-arrow.png"),
  whiteLeftArrow: require("../../assets/images/booking/white-left-arrow.png"),
  location: require("../../assets/images/booking/location.png"),
  minus: require("../../assets/images/booking/minus.png"),
  missyCooper: require("../../assets/images/booking/missy-cooper.png"),
  plus: require("../../assets/images/booking/plus.png"),
  mainPicture: require("../../assets/images/booking/main-picture.png"),
  starFillGold: require("../../assets/images/booking/star-fill-gold.png"),
  starHalfGold: require("../../assets/images/booking/star-half-gold.png"),
  starFillWhite: require("../../assets/images/booking/star-fill-white.png"),
  success: require("../../assets/images/booking/success.png"),
  cameronWilliam: require("../../assets/images/booking/cameron-william.png"),
  alfonzoSander: require("../../assets/images/booking/alfonzo-sander.png"),
  bennyBromo: require("../../assets/images/booking/benny-bromo.png"),
  danielKylee: require("../../assets/images/booking/daniel-kylee.png"),
  kevinMerrill: require("../../assets/images/booking/kevin-merrill.png"),
  pedroHuard: require("../../assets/images/booking/pedro-huard.png"),
  edgarTorrey: require("../../assets/images/booking/edgar-torrey.png"),
  christianEvvy: require("../../assets/images/booking/christian-evvy.png"),
};

export default BOOKING_IMAGES;
